import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ToastContainer } from 'react-toastify';
import Head from 'next/head';
import React, { useState } from 'react';
import Appbar from 'src/components/appbar';
import "react-toastify/dist/ReactToastify.css";
import Container from '@mui/material/Container';
import { AuthContext } from 'src/contexts/AuthContext';
import { FilterContext } from 'src/contexts/FilterContext';

import { QueryClient, QueryClientProvider } from 'react-query';
import { ThemeProvider, createTheme } from '@mui/material/styles';

import styles from 'styles/Home.module.css';

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#1976d2',
    },
  },
});

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  const [loggedInUser, setLoggedInUser] = useState({})

  //filter state 
  const [type, setType] = useState('')
  const [name, setName] = useState('')
  const [platForm, setPlatForm] = useState('')


  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider theme={darkTheme}>
        <Head>
          <title>Game </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <FilterContext.Provider value={{ type, setType, name, setName, platForm, setPlatForm }}>
          <AuthContext.Provider value={{ loggedInUser, setLoggedInUser }}>
            <div>
              <Appbar />
              <main className={styles.main}>
                <Container maxWidth="lg" sx={{ mt: '10px' }}>
                  <Component {...pageProps} />
                </Container>
              </main>

              <ToastContainer autoClose={8000} />
            </div>
          </AuthContext.Provider>
        </FilterContext.Provider>
      </ThemeProvider>
    </QueryClientProvider>
  );
}

export default MyApp;
